sudo: required

services:
  - docker

before_script: docker run --rm -v $(pwd):/app composer/composer install

script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - docker run --rm -v $(pwd):/var/www/html cbergau/clean_architecture_shop_symfony3client php ./vendor/bin/phpunit tests/ --coverage-clover=coverage.clover && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
